<template>
    <div class="loading-spinner-dual-ring">
        <div class="spinner">
            <div>
            </div>
            <div>
                <div></div>
            </div>
        </div>
    </div>
</template>

<script>
// Spinner Loading gerado através da aplicação: https://loading.io/

export default {

}
</script>

<style scoped>
    @keyframes loading {
        0% { 
            transform: rotate(0);
        }
        100% { 
            transform: rotate(360deg);
        }
    }
    .spinner div { 
        box-sizing: border-box !important;
    }
    .spinner > div {
        position: absolute;
        width: 142px;
        height: 142px;
        top: 50%;
        left: 50%;
        margin-top: -70px;
        margin-left: -70px;
        border-radius: 50%;
        border: 14px solid #000;
        border-color: #2c86dc transparent #2c86dc transparent;
        animation: loading 0.8695652173913042s linear infinite;
    }
    .spinner > div:nth-child(2) { 
        border-color: transparent;
    }
    .spinner > div:nth-child(2) div {
        position: absolute;
        width: 100%;
        height: 100%;
        transform: rotate(45deg);
    }
    .spinner > div:nth-child(2) div:before, 
    .spinner > div:nth-child(2) div:after { 
        content: "";
        display: block;
        position: absolute;
        width: 14px;
        height: 14px;
        top: -14px;
        left: 50px;
        background: #2c86dc;
        border-radius: 50%;
        box-shadow: 0 128px 0 0 #2c86dc;
    }
    .spinner > div:nth-child(2) div:after { 
        left: -14px;
        top: 50px;
        box-shadow: 128px 0 0 0 #2c86dc;
    }
    .loading-spinner-dual-ring {
        width: 100vw;
        height: 100vh;
        position: absolute;
        z-index: 1;
        display: inline-block;
        overflow: hidden;
        background: rgba(0, 0, 0, 0.8);
    }
    .spinner {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0;
    }
    .spinner div { 
        box-sizing: content-box; 
    }
    /* generated by https://loading.io/ */
</style>